spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/product-db
    username: product-db
    password: product-db1234
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  redis:
    port: 6379
    host: localhost

logging:
  pattern:
    console: "%d{YYYY-MM-DD HH:mm:ss.SSS} [%X{transactionId}] [%t] %-5level %logger{36} - %msg%n"


